---

- name: Install dependency packages
  package:
    name: "{{ proxysql_dependency_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  when: proxysql_dependency_pkgs

- name: Install pip dependency packages
  pip:
    name: "{{ proxysql_pip_dependency_pkgs }}"
    state: present
  when: proxysql_pip_dependency_pkgs

- name: Install ProxySQL from repository
  package:
    name: "{{ proxysql_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  when: proxysql_use_official_repo

- name: Install ProxySQL from DEB package
  apt:
    deb: "{{ proxysql_pkg_url }}"
    state: present
  when: >
        (not proxysql_use_official_repo) and
        (ansible_os_family == "Debian")

- name: Install ProxySQL from YUM package
  yum:
    name: "{{ proxysql_pkg_url }}"
    state: present
  when: >
        (not proxysql_use_official_repo) and
        (ansible_os_family == "RedHat")
