---

filebeat_apt_repository: "{{filebeat_repo_baseurl}}/apt"

filebeat_package:        "filebeat={{filebeat_version}}"

filebeat_package_url:    "{{filebeat_package_baseurl}}/filebeat-{{filebeat_version}}-{{filebeat_arch}}.deb"

# vi:ts=2:sw=2:et:ft=yaml
