# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

		  # Add 4 additional 30GB drives
		  box.vm.provider "virtualbox" do |vb|
			  vb.customize ["modifyvm", :id, "--memory", "1024"]
			  # Centos image doesn't come with a SATA Controller, adding it:
			  unless File.exist?(File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-1.vdi"))
				  puts "**** Adding SATA Controller; once the first disk is there asuming we don't need to do this *****"
				  vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
			  else
				  puts "*** Skipping adding the SATA Controller ***"
			  end
			end
			box.vm.provider "virtualbox" do |vb|
			unless File.exist?(File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-1.vdi"))
				["1","2","3","4"].each do |disk|
					diskname = File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-#{disk}.vdi")
					vb.customize ['createhd', '--filename', diskname, '--variant', 'Standard', '--size', 30720]
					vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', diskname]
				end
			end
		end
 	  box.vm.provision "shell", inline: <<-SHELL
mkdir -p ~root/.ssh && \
cp ~vagrant/.ssh/auth* ~root/.ssh && \
setenforce 0 && \
bash /vagrant/repo.sh
pvcreate --bootloaderareasize 1m /dev/sdb /dev/sdc /dev/sdd /dev/sde && \
vgcreate VolGroup01 /dev/sdb /dev/sdc /dev/sdd /dev/sde && \
lvcreate -L 1g VolGroup01 -n swap && \
lvcreate -L 8g VolGroup01 -n root && \
lvcreate -L 16g -m1 VolGroup01 -n var && \
lvcreate -L 8g VolGroup01 -n home && \
mkfs.ext4 /dev/VolGroup01/home && \
mkfs.ext4 /dev/VolGroup01/root && \
mkfs.ext4 /dev/VolGroup01/var && \
mkswap /dev/VolGroup01/swap && \
mkdir -p /mnt/root && \
mount /dev/VolGroup01/root /mnt/root && \
rsync -aAHX  --exclude='/dev/**' --exclude='/proc/**' --exclude='/sys/**' --exclude='/var/**' --exclude='/mnt/**' --exclude='/home/**' / /mnt/root/ ; \
mount /dev/VolGroup01/home /mnt/root/home/ && \
rsync -aAHX  /home/ /mnt/root/home/ ; \
mount /dev/VolGroup01/var /mnt/root/var && \
rsync -aAHX  /var/ /mnt/root/var/ ; \
mount -t proc /proc /mnt/root/proc ; \
mount --rbind /sys /mnt/root/sys ; \
mount --make-rslave /mnt/root/sys ; \
mount --rbind /dev /mnt/root/dev ; \
mount --make-rslave /mnt/root/dev ; \
/bin/bash /vagrant/chroot.sh
   
  	  SHELL

      end
  end
end

