---
- name: Ensure dependencies are installed.
  yum:
    name: "centos-release-gluster{{ glusterfs_default_release }}"
    state: present

- name: Ensure Gluster packages are installed.
  yum:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present

- name: Set nis_enabled flag on and keep it persistent across reboots
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes

- name: Set sefcontext for bricks
  sefcontext:
    target: '/srv/gluster(/.*)?'
    setype: glusterd_brick_t
    state: present

#- name: Copy te selinuc module
#  copy:
#    src: glusterfs.te
#    dest: /opt/glusterfs.te

#- name: generate selinux rule for glusterfs
#  shell: checkmodule -M -m -o /opt/glusterfs.mod  /opt/glusterfs.te && semodule_package -o /opt/glusterfs.pp -m /opt/glusterfs.mod && semodule -i /opt/glusterfs.pp


- name: Make override dir for service glusterd
  file:
   path: /etc/systemd/system/glusterd.service.d
   state: directory

- name: Enable autorestart of services
  copy:
   src: override.conf
   dest: /etc/systemd/system/glusterd.service.d/override.conf

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  systemd: name=firewalld state=restarted enabled=yes

- name: Firewalld add Gluster zone
  firewalld:
   zone: gluster
   state: present
   permanent: true

- name: Firewalld service state
  systemd: name=firewalld state=reloaded enabled=yes

- name: Firewalld add trusted ip to Gluster zone
  firewalld:
   source: "{{ hostvars[ groups['webservers'][0] ].ansible_ssh_host }}"
   zone: gluster
   state: enabled
   permanent: true
   immediate: true

- name: Firewalld add trusted ip to Gluster zone
  firewalld:
   source: "{{ hostvars[ groups['webservers'][1] ].ansible_ssh_host }}"
   zone: gluster
   state: enabled
   permanent: true
   immediate: true

- name: Firewalld add trusted ip to Gluster zone
  firewalld:
   source: "{{ hostvars[ groups['webservers'][2] ].ansible_ssh_host }}"
   zone: gluster
   state: enabled
   permanent: true
   immediate: true

- name: firewalld open Gluster ports
  firewalld:
   service: glusterfs
   zone: gluster
   permanent: true
   immediate: true
   state: enabled

- name: firewalld open Gluster ports
  firewalld:
   service: rpc-bind
   zone: gluster
   permanent: true
   immediate: true
   state: enabled

- name: firewalld open Gluster ports
  firewalld:
   port: 24010/tcp
   zone: gluster
   permanent: true
   immediate: true
   state: enabled
