- hosts: master
  become: yes
  roles:
   - tls_asterisk

   
- hosts: slave1, slave2
  become: yes
  tasks:
  - name: Install various groups of packages
    yum:
     name: "{{ item }}"
     state: present
    with_items:
    - xorg-x11-xauth
    - dbus-x11
  - name: Install zoiper
    shell: yum install /vagrant/zoiper5_5.2.19_x86_64.rpm -y
    
