# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:balancer1 => {
               :box_name => "centos/7",
               :public => {:ip => '192.168.0.110', :adapter => 3 },
               :net => [
                        {ip: '10.0.5.10', adapter: 2, netmask: "255.255.255.0"},
                       ]
 },
	
:balancer2 => {
               :box_name => "centos/7",
               :public => {:ip => '192.168.0.111', :adapter => 3 },
               :net => [
					   {ip: '10.0.5.11', adapter: 2, netmask: "255.255.255.0"},
                       ]
                      
 },

:web1 => {
          :box_name => "centos/7",
          :public => {:ip => '192.168.0.120', :adapter => 3 },
          :net => [
                  {ip: '10.0.5.20', adapter: 2, netmask: "255.255.255.0"},
                  ]
 },

:web2 => {
		:box_name => "centos/7",
		:public => {:ip => '192.168.0.121', :adapter => 3 },
		:net => [
				{ip: '10.0.5.21', adapter: 2, netmask: "255.255.255.0"},
				]
 },

	
:clcontrol => {
		:box_name => "centos/7",
		:public => {:ip => '192.168.0.130', :adapter => 3 },
		:net => [
				{ip: '10.0.5.30', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:cluster1 => {
		:box_name => "centos/7",
		:public => {:ip => '192.168.0.131', :adapter => 3 },
		:net => [
				{ip: '10.0.5.31', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:cluster2 => {
		:box_name => "centos/7",
		:public => {:ip => '192.168.0.132', :adapter => 3 },
		:net => [
				{ip: '10.0.5.32', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:cluster3 => {
		:box_name => "centos/7",
		:public => {:ip => '192.168.0.133', :adapter => 3 },
		:net => [
				{ip: '10.0.5.33', adapter: 2, netmask: "255.255.255.0"},
				]
 },

}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

		config.vm.provision "ansible" do |ansible|
			ansible.verbose = "vvv"
			ansible.playbook = "provisioning/playbook.yml"
			ansible.become = "true"
			ansible.inventory_path = "provisioning/hosts.bridge"
		end
		
		config.vm.provider "virtualbox" do |v|
			v.memory = 256
		end


      end

  end
  
  
end

