# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:balancer1 => {
               :box_name => "centos/7",
               :net => [
              #              {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "router-net"},
                       {ip: '10.0.5.10', adapter: 2, netmask: "255.255.255.0"},
                       ]
 },
	
:balancer2 => {
               :box_name => "centos/7",
               :net => [
					   {ip: '10.0.5.11', adapter: 2, netmask: "255.255.255.0"},
                       ]
                      
 },

:web1 => {
          :box_name => "centos/7",
          :net => [
                  {ip: '10.0.5.20', adapter: 2, netmask: "255.255.255.0"},
                  ]
 },
	
:web2 => {
		:box_name => "centos/7",
		:net => [
				{ip: '10.0.5.21', adapter: 2, netmask: "255.255.255.240"},
				]
 },

}
#    :public => {:ip => '192.168.0.254', :adapter => 3 }, 

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

		config.vm.provision "ansible" do |ansible|
			ansible.verbose = "vvv"
			ansible.playbook = "provisioning/playbook.yml"
			ansible.become = "true"
			ansible.inventory_path = "provisioning/hosts"
		end
		
		config.vm.provider "virtualbox" do |v|
			v.memory = 256
		end


      end

  end
  
  
end

