# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:"balancer1.tld" => {
               :box_name => "centos/7",
#               :public => {:ip => '192.168.0.111', :adapter => 3 },
               :net => [
                        {ip: '10.0.5.11', adapter: 2, netmask: "255.255.255.0"},
                       ]
 },
	
:"balancer2.tld" => {
               :box_name => "centos/7",
#               :public => {:ip => '192.168.0.112', :adapter => 3 },
               :net => [
					   {ip: '10.0.5.12', adapter: 2, netmask: "255.255.255.0"},
                       ]
                      
 },

:"web1.tld" => {
          :box_name => "centos/7",
#          :public => {:ip => '192.168.0.121', :adapter => 3 },
          :net => [
                  {ip: '10.0.5.21', adapter: 2, netmask: "255.255.255.0"},
                  ]
 },

:"web2.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.122', :adapter => 3 },
		:net => [
				{ip: '10.0.5.22', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:"web3.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.123', :adapter => 3 },
		:net => [
				{ip: '10.0.5.23', adapter: 2, netmask: "255.255.255.0"},
				]
 },
#:clcontrol => {
#		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.130', :adapter => 3 },
#		:net => [
#				{ip: '10.0.5.30', adapter: 2, netmask: "255.255.255.0"},
#				]
# },

:"cluster1.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.131', :adapter => 3 },
		:net => [
				{ip: '10.0.5.31', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:"cluster2.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.132', :adapter => 3 },
		:net => [
				{ip: '10.0.5.32', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:"cluster3.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.133', :adapter => 3 },
		:net => [
				{ip: '10.0.5.33', adapter: 2, netmask: "255.255.255.0"},
				]
 },

:"log1.tld" => {
		:box_name => "centos/7",
#		:public => {:ip => '192.168.0.141', :adapter => 3 },
		:net => [
				{ip: '10.0.5.41', adapter: 2, netmask: "255.255.255.0"},
				]
 },
	
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
		# wait until all server is up, then provision
		#if box.vm.hostname == "log1"
		config.vm.provision "ansible" do |ansible|
			#ansible.verbose = "vvv"
			ansible.playbook = "provisioning/playbook.yml"
			ansible.become = "true"
			ansible.inventory_path = "provisioning/hosts"
			# Disable default limits to connect to all the machines
			ansible.limit = "all"
		 #end
		end
		if box.vm.hostname == "log1.tld"
			box.vm.provider "virtualbox" do |v|
			v.memory = 2048
			end
		else
			box.vm.provider "virtualbox" do |v|
			v.memory = 512
			end
		end


      end

  end
  
  
end

