---

- name: Download SRTP
  unarchive:
      src: https://downloads.sourceforge.net/project/srtp/srtp/1.4.4/srtp-1.4.4.tgz 
      dest: /opt
      remote_src: yes

- name: Fix test script
  lineinfile:
      path: /opt/srtp/test/rtpw_test.sh
      regexp: "RTPW=rtpw"
      line: "RTPW=./rtpw"

- name: Install SRTP
  command: "{{ item }} chdir=/opt/srtp"
  with_items:
    - autoconf 
    - ./configure CFLAGS=-fPIC --prefix=/usr  
    - make 
    - make runtest
    - make uninstall
    - make install
    - ldconfig

