---
# Tasks specific for RedHat systems

- name: "RedHat | Use Zabbix package name"
  set_fact:
    zabbix_server_package: "zabbix-server-{{ zabbix_server_database }}"
  when:
    - zabbix_repo == "zabbix"
  tags:
    - zabbix-server

- name: "RedHat | Use EPEL package name"
  set_fact:
    zabbix_server_package: "zabbix{{ zabbix_short_version }}-server-{{ zabbix_server_database }}"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-server

- name: "RedHat | Set some facts EPEL"
  set_fact:
    datafiles_path: "/usr/share/zabbix-{{ zabbix_server_database_long }}"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-server

- name: "RedHat | Set some facts Zabbix < 3.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-server-{{ zabbix_server_database }}-{{ zabbix_version }}*/create"
  when:
    - zabbix_version is version_compare('3.0', '<')
  tags:
    - zabbix-server

- name: "RedHat | Set facts for Zabbix >= 3.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-server-{{ zabbix_server_database }}-{{ zabbix_version }}*"
  when:
    - zabbix_version is version_compare('3.0', '>=')
  tags:
    - zabbix-server

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  tags:
    - zabbix-server

- name: "RedHat | Installing zabbix-server-{{ zabbix_server_database }}"
  yum:
    pkg: "{{ zabbix_server_package }}"
    state: present
  tags:
    - zabbix-server

- name: "RedHat | Install Ansible module dependencies"
  yum:
    name: python-psycopg2
    state: present
  when:
    - zabbix_database_creation
    - zabbix_server_database == 'pgsql'
  tags:
    - zabbix-server

- name: "RedHat | Install Mysql Client package RHEL7"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - MySQL-python
  when:
    - zabbix_server_database == 'mysql'
    - ansible_distribution_major_version == "7"
  tags:
    - zabbix-server

- name: "RedHat | Install Mysql Client package RHEL5 - 6"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql
    - MySQL-python
  when:
    - zabbix_server_database == 'mysql'
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "5"
  tags:
    - zabbix-server

- name: "RedHat | Install PostgreSQL client package"
  yum:
    name: postgresql
    state: present
  when:
    - zabbix_server_database == 'pgsql'
  tags:
    - zabbix-server

- name: "RedHat | Install related SELinux package"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libsemanage-python
  when:
    - selinux_allow_zabbix_can_network
  tags:
    - zabbix-server

- name: "RedHat | Enable httpd_can_connect_zabbix SELinux boolean"
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_can_connect_zabbix
  when:
    - selinux_allow_zabbix_can_http
  tags:
    - zabbix-server

- name: "RedHat | Enable zabbix_can_network SELinux boolean"
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - zabbix_can_network
  when:
    - selinux_allow_zabbix_can_network
  tags:
    - zabbix-server
