# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 30720,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                   :size => 30720, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                           :size => 30720,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                           :size => 30720, # Megabytes
                        :port => 4
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
#				  vb.customize ["modifyvm", :id, "--firmware", "efi"]
		  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]

		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Standard', '--size', dconf[:size]]
			  end
			  vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

		  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh 
      yum install -y mdadm smartmontools hdparm gdisk 
      
      echo 'start=     2048, size=     4096, Id=83' |  sfdisk /dev/sdb && \
      echo 'start=     6144, size=  1048576, Id=83, bootable' |  sfdisk /dev/sdb && \
      echo 'start=  1054720, size= 61859840, Id=83' |  sfdisk /dev/sdb && \
      pvcreate /dev/sdb3 /dev/sdc /dev/sdd && \
      vgcreate VolGroup01 /dev/sdb3 /dev/sdc /dev/sdd && \
      lvcreate -L 2g VolGroup01 -n swap && \
      lvcreate -L 8g VolGroup01 -n root && \
      lvcreate -L 16g -m1 VolGroup01 -n var && \
      lvcreate -L 8g VolGroup01 -n home && \
      mkfs.ext4 /dev/VolGroup01/home && \
      mkfs.ext4 /dev/VolGroup01/root && \
      mkfs.ext4 /dev/VolGroup01/var && \
      mkswap /dev/VolGroup01/swap && \
      mkdir -p /mnt/root && \
      mount /dev/VolGroup01/root /mnt/root && \
      rsync -aAHX  --exclude='/dev/**' --exclude='/proc/**' --exclude='/sys/**' --exclude='/boot/**' --exclude='/var/**' --exclude='/mnt/**' --exclude='/home/**' / /mnt/root/ && \
      mount /dev/VolGroup01/home /mnt/root/home/ && \
      rsync -aAHX  /home/ /mnt/root/home/ && \
      mkdir -p /mnt/root/var && \
      mount /dev/VolGroup01/var /mnt/root/var && \
      rsync -aAHX  /var/ /mnt/root/var/ && \
      mkfs.ext4 /dev/sdb2 && \
      mount /dev/sdb2 /mnt/root/boot && \
      rsync -aAHX /boot/  /mnt/root/boot/ && \
      grub2-install  /dev/sdb && \      
      echo /dev/sdb2 /boot ext4  rw,user,exec 0 0 >> /etc/fstab
      echo /dev/mapper/VolGroup01-root / ext4  rw,user,exec 0 0 >> /etc/fstab
      echo /dev/mapper/VolGroup01-home /home ext4  rw,user,exec 0 0 >> /etc/fstab
      echo /dev/mapper/VolGroup01-swap swap swap defaults 0 0 >> /etc/fstab
      
      lvcreate -L 8g -s -n home-snap /dev/VolGroup01/home && \
      
      
  	  SHELL

      end
  end
end

