# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

		  # Add 4 additional 30GB drives
		  box.vm.provider "virtualbox" do |vb|
			  vb.customize ["modifyvm", :id, "--memory", "1024"]
			  # Centos image doesn't come with a SATA Controller, adding it:
			  unless File.exist?(File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-1.vdi"))
				  puts "**** Adding SATA Controller; once the first disk is there asuming we don't need to do this *****"
				  vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
			  else
				  puts "*** Skipping adding the SATA Controller ***"
			  end
			end
			box.vm.provider "virtualbox" do |vb|
			unless File.exist?(File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-1.vdi"))
				["1","2","3","4"].each do |disk|
					diskname = File.expand_path("~/VirtualBox\ VMs/#{box.vm.hostname}-#{disk}.vdi")
					vb.customize ['createhd', '--filename', diskname, '--variant', 'Standard', '--size', 30720]
					vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', diskname]
				end
			end
		end
 	  box.vm.provision "shell", inline: <<-SHELL
mkdir -p ~root/.ssh && \
cp ~vagrant/.ssh/auth* ~root/.ssh && \
yum install -y mdadm smartmontools hdparm gdisk && \
setenforce 0 && \
echo -e 'o\nn\n\n\n\n+2M\nn\n\n\n\n+512M\nn\n\n\n\n\nw' | fdisk /dev/sdb  && \
grub2-install  /dev/sdb && \
pvcreate /dev/sdb3 /dev/sdc /dev/sdd && \
vgcreate VolGroup01 /dev/sdb3 /dev/sdc /dev/sdd && \
lvcreate -L 512m VolGroup01 -n swap && \
lvcreate -L 8g VolGroup01 -n root && \
lvcreate -L 512m -m1 VolGroup01 -n var && \
lvcreate -L 512m VolGroup01 -n home && \
mkfs.ext4 /dev/VolGroup01/home && \
mkfs.ext4 /dev/VolGroup01/root && \
mkfs.ext4 /dev/VolGroup01/var && \
mkswap /dev/VolGroup01/swap && \
mkdir -p /mnt/root && \
mount /dev/VolGroup01/root /mnt/root && \
rsync -aAHX  --exclude='/dev/**' --exclude='/proc/**' --exclude='/sys/**' --exclude='/boot/**' --exclude='/var/**' --exclude='/mnt/**' --exclude='/home/**' / /mnt/root/ ; \
mount /dev/VolGroup01/home /mnt/root/home/ && \
rsync -aAHX  /home/ /mnt/root/home/ ; \
mount /dev/VolGroup01/var /mnt/root/var && \
rsync -aAHX  /var/ /mnt/root/var/ ; \
mkfs.ext4 /dev/sdb2 && \
mount /dev/sdb2 /mnt/root/boot && \
rsync -aAHX /boot/  /mnt/root/boot/ ; \
mount -t proc /proc /mnt/root/proc ; \
mount --rbind /sys /mnt/root/sys ; \
mount --make-rslave /mnt/root/sys ; \
mount --rbind /dev /mnt/root/dev ; \
mount --make-rslave /mnt/root/dev ; \
chroot /mnt/root /bin/bash -c "echo UUID=`blkid -o value -s UUID /dev/sdb2` /boot ext4  defaults 0 0 > /etc/fstab  ; \ 
echo /dev/mapper/VolGroup01-root / ext4  defaults 0 0 >> /etc/fstab ; \
echo /dev/mapper/VolGroup01-home /home ext4  defaults 0 0 >> /etc/fstab ; \
echo /dev/mapper/VolGroup01-swap swap swap defaults 0 0 >> /etc/fstab ; \
echo /dev/mapper/VolGroup01-var /var ext4  defaults 0 0 >> /etc/fstab ; \
find /etc/default/grub -type f -print0 | xargs -0 sed -i 's/GRUB_CMDLINE_LINUX/#GRUB_CMDLINE_LINUX/g' ; \
echo 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 crashkernel=auto rd.lvm.lv=VolGroup01/root rd.lvm.lv=VolGroup01/var rd.lvm.lv=VolGroup01/home rd.lvm.lv=VolGroup01/swap selinux=0"' >> /etc/default/grub ; \
grub2-mkconfig -o /boot/grub2/grub.cfg"
   
  	  SHELL

      end
  end
end

