---
- name: Add backup group
  group:
   name: "{{ ftp_backup_user }}"
   gid: 1250

- name: Add backup user
  user:
   name: "{{ ftp_backup_user }}"
   group: "{{ ftp_backup_user }}"
   home: "{{ ftp_backup_home }}"
   uid: 1250

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}/cluster3"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}/web2"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Change ownership of backup installation
  file: path="{{ ftp_backup_home }}/" owner={{ ftp_backup_user }} group={{ ftp_backup_user }} state=directory recurse=yes

- name: Install dependency packages for backup
  yum:
    name:
     - epel-release
    state: present

- name: Install dependency packages for backup
  yum:
    name:
     - proftpd
     - perl
    state: present

- name: Make proftpd dir
  file:
   path: /etc/proftpd
   state: directory
   mode: 0755

- name: copy ftpasswd script
  copy:
   src: ftpasswd
   dest: /etc/proftpd/ftpasswd
   mode: 0755

- name: copy proftpd.conf script
  copy:
   src: proftpd.conf
   dest: /etc/proftpd.conf
   mode: 0640

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes

# Fix suspected race between firewalld and polkit BZ1436964
- name: Wait for polkit action to have been created
  command: pkaction --action-id=org.fedoraproject.FirewallD1.config.info
  ignore_errors: true
  register: pkaction
  changed_when: false
  until: pkaction.rc == 0
  retries: 6
  delay: 10

- name: firewalld open ftp
  firewalld:
   service: ftp
   permanent: true
   immediate: true
   state: enabled

- name: Setup ftp user
  shell: cd /etc/proftpd/ && echo  {{ ftp_backup_password }} | /etc/proftpd/ftpasswd --passwd --name={{ ftp_backup_user }} --uid=1250 --home={{ ftp_backup_dir }} --shell=/sbin/nologin --stdin
  tags:
  - skip_ansible_lint

- name: Set mode to ftpd.passwd
  file:
   path: /etc/proftpd/ftpd.passwd
   mode: 0600

- name: Proftpd service state
  service: name=proftpd state=started enabled=yes
