---
- name: Add backup group
  group:
   name: "{{ ftp_backup_user }}"
   gid: 1250

- name: Add backup user
  user:
   name: "{{ ftp_backup_user }}"
   group: "{{ ftp_backup_user }}"
   home: "{{ ftp_backup_home }}"
   uid: 1250

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}/cluster3.tld"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Make backup dir
  file:
   path: "{{ ftp_backup_dir }}/web2.tld"
   state: directory
   owner: "{{ ftp_backup_user }}"
   mode: 0755

- name: Change ownership of backup installation
  file: path="{{ ftp_backup_home }}/" owner={{ ftp_backup_user }} group={{ ftp_backup_user }} state=directory recurse=yes

- name: Install dependency packages for backup
  yum:
    name:
     - epel-release
    state: present

- name: Install dependency packages for backup
  yum:
    name:
     - proftpd
     - perl
    state: present

- name: Copy te selinuc module
  copy:
    src: proftpdse.te
    dest: /opt/proftpdse.te

- name: generate selinux rule for proftpd
  shell: checkmodule -M -m -o /opt/proftpdse.mod  /opt/proftpdse.te && semodule_package -o /opt/proftpdse.pp -m /opt/proftpdse.mod && semodule -i /opt/proftpdse.pp
  tags:
  - skip_ansible_lint

- name: Make override dir for service proftpd
  file:
   path: /etc/systemd/system/proftpd.service.d
   state: directory

- name: Enable autorestart of services
  copy:
   src: override.conf
   dest: /etc/systemd/system/proftpd.service.d/override.conf

- name: Make proftpd dir
  file:
   path: /etc/proftpd
   state: directory
   mode: 0755

- name: copy ftpasswd script
  copy:
   src: ftpasswd
   dest: /etc/proftpd/ftpasswd
   mode: 0755

- name: copy proftpd.conf script
  copy:
   src: proftpd.conf
   dest: /etc/proftpd.conf
   mode: 0640

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=restarted enabled=yes

- name: firewalld open ftp
  firewalld:
   service: ftp
   permanent: true
   state: enabled

- name: Firewalld service state
  service: name=firewalld state=reloaded enabled=yes

- name: Setup ftp user
  shell: cd /etc/proftpd/ && echo  {{ ftp_backup_password }} | /etc/proftpd/ftpasswd --passwd --name={{ ftp_backup_user }} --uid=1250 --home={{ ftp_backup_dir }} --shell=/sbin/nologin --stdin
  tags:
  - skip_ansible_lint

- name: Set mode to ftpd.passwd
  file:
   path: /etc/proftpd/ftpd.passwd
   mode: 0600

- name: Proftpd service state
  service: name=proftpd state=restarted enabled=yes
