---
# ProxySQL
#proxysql_version: 1.4.12
proxysql_use_official_repo: True
proxysql_login_admin_user: "admin"
proxysql_login_admin_password: "{{ lookup('password', '/tmp/mysqlpasswordfile_proxy_admin chars=ascii_letters,digits length=15') }}"
proxysql_login_admin_host: 0.0.0.0
proxysql_login_admin_port: 6032

proxysql_username_monitor: "monitor"
proxysql_password_monitor: "{{ lookup('password', '/tmp/mysqlpasswordfile_proxy_monitor chars=ascii_letters,digits length=15') }}"

proxysql_cluster_username: "cluster"
proxysql_cluster_password: "{{ lookup('password', '/tmp/mysqlpasswordfile_proxy_cluster chars=ascii_letters,digits length=15') }}"

proxysql_nodes_group: proxysql

# see https://github.com/sysown/proxysql/issues/1422
proxysql_global_variables_kv:
 admin-admin_credentials: "{{ proxysql_login_admin_user }}:{{ proxysql_login_admin_password }};{{ proxysql_cluster_username }}:{{ proxysql_cluster_password }}"
 admin-mysql_ifaces: "{{ proxysql_login_admin_host }}:{{ proxysql_login_admin_port }}"
 admin-cluster_username: "{{ proxysql_cluster_username }}"
 admin-cluster_password: "{{ proxysql_cluster_password }}"
 mysql-default_charset: "{{ xtradb_character_set_server }}"
 mysql-interfaces: 127.0.0.1:3306;/var/run/proxysql.sock
 mysql-max_connections: 8192
 mysql-monitor_username: "{{ proxysql_username_monitor }}"
 mysql-monitor_password: "{{ proxysql_password_monitor }}"
 mysql-server_version: 5.7.23

proxysql_backend_servers:
 mysql-srv1-hg1:
  comment: mysql-srv1-hg1
  hostgroup: 1
  hostname: "{{ xtradb_master_node }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  max_connections: 200
  status: ONLINE
  weight: 1000
 mysql-srv1-hg2:
  comment: mysql-srv1-hg2
  hostgroup: 2
  hostname: "{{ xtradb_master_node }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  max_connections: 200
  status: ONLINE
  weight: 1000
  read_only: 0
 mysql-srv2-hg2:
  comment: mysql-srv2-hg2
  hostgroup: 2
  hostname: "{{ hostvars[ groups[xtradb_nodes_group][1] ].ansible_ssh_host }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  max_connections: 200
  status: ONLINE
  weight: 1000
  read_only: 0
 mysql-srv3-hg2:
  comment: mysql-srv3-hg2
  hostgroup: 2
  hostname: "{{ hostvars[ groups[xtradb_nodes_group][2] ].ansible_ssh_host }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  max_connections: 200
  status: ONLINE
  weight: 1000
  read_only: 0
proxysql_proxysql_servers:
 proxysql-srv-1:
  comment: proxysql-srv-1
  hostname: "{{ hostvars[ groups[proxysql_nodes_group][0] ].ansible_ssh_host }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  port: 6032
  weight: 0
 proxysql-srv-2:
  comment: proxysql-srv-2
  hostname: "{{ hostvars[ groups[proxysql_nodes_group][1] ].ansible_ssh_host }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  port: 6032
  weight: 0
 proxysql-srv-3:
  comment: proxysql-srv-3
  hostname: "{{ hostvars[ groups[proxysql_nodes_group][2] ].ansible_ssh_host }}"
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  port: 6032
  weight: 0
proxysql_replication_hostgroups:
 Cluster:
  comment: Cluster
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  reader_hostgroup: 2
  writer_hostgroup: 1
proxysql_mysql_users:
 user1:
  active: 1
  backend: 1
  default_hostgroup: 1
  fast_forward: 0
  frontend: 1
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  max_connections: 1000
  password: "{{ wp_db_password }}"
  transaction_persistent: 1
  username: "{{ wp_db_user }}"
proxysql_query_rules:
 catchall:
  active: 1
  apply: 1
  destination_hostgroup: 1
  flagIN: 0
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  match_pattern: .*@.*
  negate_match_pattern: 0
  rule_id: 1
 selectforupdate:
  active: 1
  apply: 1
  destination_hostgroup: 1
  flagIN: 0
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  match_pattern: ^SELECT.*FOR UPDATE
  negate_match_pattern: 0
  rule_id: 2
 select:
  active: 1
  apply: 0
  destination_hostgroup: 2
  flagIN: 0
  login_host: "{{ proxysql_login_admin_host }}"
  login_password: "{{ proxysql_login_admin_password }}"
  login_port: "{{ proxysql_login_admin_port }}"
  login_user: "{{ proxysql_login_admin_user }}"
  match_pattern: ^SELECT.*
  negate_match_pattern: 0
  rule_id: 3
