# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.255.5', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "wi-fi-net"},
                   {ip: '192.168.255.6', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  
#:centralServer => {
#        :box_name => "centos/7",
#        :net => [
#					{ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
#                    {adapter: 3, auto_config: false, virtualbox__intnet: true},
#					{adapter: 4, auto_config: false, virtualbox__intnet: true},
#                ]
# },
	
:office1Router => {
          :box_name => "centos/7",
          :net => [
                      {ip: '192.168.254.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                      {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dev-net"},
                      {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "testserv-net"},
                      {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "mng-net"},
                      {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                      {ip: '192.168.253.9', adapter: 7, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
                  ]
 },

#:office1Server => {
#          :box_name => "centos/7",
#          :net => [
#                      {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dev-net"},
#					{adapter: 3, auto_config: false, virtualbox__intnet: true},
#                 ]
#},

#:office2Router => {
#          :box_name => "centos/7",
#          :net => [
#                   {ip: '192.168.253.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
#                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
#                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "testserv-net"},
#                   {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
#                  ]
# },
	
#:office2Server => {
#          :box_name => "centos/7",
#          :net => [
#                      {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
#						{adapter: 3, auto_config: false, virtualbox__intnet: true},
#                     ]
# },

:testServer1 => {
    :box_name => "centos/7",
    :net => [
        {ip: '192.168.253.10', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
        {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
    ]
},

:testClient1 => {
    :box_name => "centos/7",
    :net => [
        {ip: '192.168.253.11', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
        {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
    ]
},


:testServer2 => {
    :box_name => "centos/7",
    :net => [
        {ip: '192.168.253.10', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
        {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
    ]
},

:testClient2 => {
    :box_name => "centos/7",
    :net => [
        {ip: '192.168.253.12', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
        {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLAN"},
    ]
},

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
		case boxname.to_s
		when "inetRouter"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.conf
			sysctl -p
			iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
			echo "192.168.0.0/16 via 192.168.255.2" >  /etc/sysconfig/network-scripts/route-bond0
      echo -e 'DEVICE="bond0"\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPADDR=192.168.255.1\nPREFIX=30\nBOOTPROTO=static\nBONDING_OPTS="mode=1 miimon=100"' > /etc/sysconfig/network-scripts/ifcfg-bond0
      echo -e 'DEVICE="eth1"\nONBOOT=yes\nSLAVE=yes\nMASTER=bond0\nBOOTPROTO=none' > /etc/sysconfig/network-scripts/ifcfg-eth1
      echo -e 'DEVICE="eth2"\nONBOOT=yes\nSLAVE=yes\nMASTER=bond0\nBOOTPROTO=none' > /etc/sysconfig/network-scripts/ifcfg-eth2
			service network restart
			SHELL
		when "centralRouter"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
			sysctl --system
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			cp /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-bond0:1
			find /etc/sysconfig/network-scripts/ifcfg-eth1:1 -type f -print0 | xargs -0 sed -i 's/eth1/bond0\:1/g'
			find /etc/sysconfig/network-scripts/ifcfg-eth1:1 -type f -print0 | xargs -0 sed -i 's/192\.168\.255\.2/192.168.254.1/g'
			cp /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-bond0:2
			find /etc/sysconfig/network-scripts/ifcfg-eth1:2 -type f -print0 | xargs -0 sed -i 's/eth1/bond0\:2/g'
			find /etc/sysconfig/network-scripts/ifcfg-eth1:2 -type f -print0 | xargs -0 sed -i 's/192\.168\.255\.2/192.168.253.1/g'
			echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-bond0
			echo "192.168.2.0/24 via 192.168.254.2" >  /etc/sysconfig/network-scripts/route-eth1
			echo "192.168.1.0/24 via 192.168.253.2" >> /etc/sysconfig/network-scripts/route-eth1
      echo -e 'DEVICE="bond0"\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPADDR=192.168.255.2\nPREFIX=30\nBOOTPROTO=static\nBONDING_OPTS="mode=1 miimon=100"' > /etc/sysconfig/network-scripts/ifcfg-bond0
      echo -e 'DEVICE="eth1"\nONBOOT=yes\nSLAVE=yes\nMASTER=bond0\nBOOTPROTO=none' > /etc/sysconfig/network-scripts/ifcfg-eth1
      echo -e 'DEVICE="eth5"\nONBOOT=yes\nSLAVE=yes\nMASTER=bond0\nBOOTPROTO=none' > /etc/sysconfig/network-scripts/ifcfg-eth5
			systemctl restart network
			SHELL
#		when "centralServer"
#			box.vm.provision "shell", inline: <<-SHELL
#			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
#			echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
#			systemctl restart network
#			SHELL
		when "office1Router"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
			sysctl --system
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.254.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			systemctl restart network
			SHELL
#		when "office1Server"
#			box.vm.provision "shell", inline: <<-SHELL
#			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
#			echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
#			systemctl restart network
#			SHELL
#		when "office2Router"
#			box.vm.provision "shell", inline: <<-SHELL
#			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
#			sysctl --system
#			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
#			echo "GATEWAY=192.168.253.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
#			systemctl restart network
#			SHELL
#		when "office2Server"
#			box.vm.provision "shell", inline: <<-SHELL
#			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
#			echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
#			systemctl restart network
#			SHELL
    when "testServer1"
        box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.253.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      echo "VLAN=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth2
			systemctl restart network
      SHELL
    when "testServer2"
        box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.253.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      echo "VLAN=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth2
			systemctl restart network
      SHELL
      when "testClient1"
        box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.253.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      echo "VLAN=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth2
			systemctl restart network
        SHELL
      when "testClient2"
        box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.253.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
      echo "VLAN=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth2
			systemctl restart network
        SHELL
    end

      end

  end
  
  
end

