---
- hosts: all
  become: yes
  roles:
   - ipa-hosts
   - ssh-ldap
  tasks:
  - name: disable selinux
    shell: setenforce 0
  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
     - nmap
     - nano
     - policycoreutils-python
     
- hosts: centralrouter,inetrouter,inetrouter2
  become: yes
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
     - ipa-client
     
     
- hosts: inetrouter
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=inetrouter.otus.lan
    
- hosts: inetrouter2
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=inetrouter2.otus.lan

- hosts: centralrouter
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=centralrouter.otus.lan
    
- hosts: centralserver
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=centralserver.otus.lan
    

    
- hosts: inetrouter
  become: yes
  roles:
   - ip_forwarding
  tasks:
  - name: install gateway
    shell: echo "192.168.0.0/16 via 192.168.255.2" >  /etc/sysconfig/network-scripts/route-eth1
  - name: Restart Network
    service: name=network state=restarted  
  - name: add iptables
    shell: /sbin/iptables-restore < /vagrant/provisioning/iptables_inetRouter.rules
  - name: save iptables
    shell: service iptables save

- hosts: inetrouter
  become: yes
  roles:
   - freeipa-client
    
    
- hosts: inetrouter2
  become: yes
  roles:
   - ip_forwarding
  tasks:
  - name: Install Firewalld
    yum: name=firewalld state=present
  - name: Firewalld service state start
    service: name=firewalld state=started enabled=yes
  - name: install gateway
    shell: echo "192.168.1.0/24 via 192.168.255.6" >  /etc/sysconfig/network-scripts/route-eth1
  - name: firewalld open 443
    firewalld:
     service: https
     state: enabled
     permanent: true
     immediate: true
  - name: firewalld add masquerade
    firewalld:
     masquerade: yes
     state: enabled
     permanent: true
     immediate: true
     zone: public
  - name: firewalld add port redirect
    firewalld:
     rich_rule: 'rule family=ipv4 forward-port port=443 protocol=tcp to-port=443 to-addr=192.168.1.2'
     zone: public
     state: enabled
     immediate: true
     permanent: true
  - name: Restart Network
    service: name=network state=restarted

- hosts: inetrouter2
  become: yes
  roles:
   - freeipa-client

    
    
- hosts: centralrouter
  become: yes
  roles:
   - ip_forwarding
   - freeipa-client
   - disable_defroute_vagrant
  tasks:
  - name: install gateway
    shell: echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth3
  - name: Restart Network
    service: name=network state=restarted
    
- hosts: centralserver
  become: yes
  roles:
   - freeipa-server
  tasks:
  - name: install gateway
    shell: echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  - name: Restart Network
    service: name=network state=restarted

- hosts: centralserver
  become: yes
  roles:
   - disable_defroute_vagrant
