---
 - name: Creates root config directory
   file: path=/root/.config/ state=directory
 - name: Creates vagrant config directory
   file: path=/home/vagrant/.config/ state=directory
 - name: Creates liquidprompt directory
   file: path=/opt/liquidprompt/ state=directory
 - name: copy liquidpromp
   copy: src=liquidprompt dest=/opt/liquidprompt/liquidprompt owner=root group=root mode=0755
 - name: copy liquidpromprc for root
   copy: src=liquidpromptrc dest=/root/.config/liquidpromptrc owner=root group=root mode=0600
 - name: copy liquidpromprc for vagrant
   copy: src=liquidpromptrc dest=/home/vagrant/.config/liquidpromptrc owner=vagrant group=vagrant mode=0600
 - name: copy bashrc for root
   copy: src=bashrc dest=/root/.bashrc owner=root group=root mode=0600   
 - name: copy bashrc for vagrant
   copy: src=bashrc dest=/home/.bashrc owner=vagrant group=vagrant mode=0600   
