---
- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  systemd: name=firewalld state=restarted enabled=yes

- name: Firewalld add keepalived zone
  firewalld:
   zone: keepalived
   state: present
   permanent: true

- name: Firewalld service state
  systemd: name=firewalld state=reloaded enabled=yes

- name: copy service VRRP
  copy:
   src: VRRP.xml
   dest: /tmp/VRRP.xml

- name: Add service from file
  shell: firewall-cmd --permanent --new-service-from-file=/tmp/VRRP.xml
  ignore_errors: yes
  tags:
  - skip_ansible_lint

- name: Firewalld add trusted ip to keepalived zone
  firewalld:
   source: "{{ hostvars[ groups['lblservers'][0] ].ansible_ssh_host }}"
   zone: keepalived
   state: enabled
   permanent: true
   immediate: true

- name: Firewalld add trusted ip to keepalived zone
  firewalld:
   source: "{{ hostvars[ groups['lblservers'][1] ].ansible_ssh_host }}"
   zone: keepalived
   state: enabled
   permanent: true
   immediate: true

- name: firewalld activate VRRP service
  firewalld:
   service: VRRP
   zone: keepalived
   permanent: true
   state: enabled

- name: Firewalld service state
  systemd: name=firewalld state=reloaded enabled=yes
