# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 250,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 250, # Megabytes
                        :port => 4
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
		  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]

		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
			  end
			  vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

		  end
          end
		  # скрипт сразу создаёт raid 5. Сохраняет конфиг. Создаёт 5 разделов, создаёт на них фс и монтирует в 5 cозданных директориий и добавляет всё в fstab.
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
	      cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
	      mdadm --create --verbose /dev/md0 --level=5 --raid-devices=3 /dev/sd[b-d] --spare-devices=1 /dev/sde && mdadm --detail --scan >> /etc/mdadm.conf && sgdisk -og  /dev/md0  && sgdisk  -n 1:1M:99M -n 2:0:+99M -n 3:0:+99M  -n 4:0:+99M  -N 5 -t 1:fd00 -t 2:fd00 -t 3:fd00 -t 4:fd00 -t 5:fd00  /dev/md0 && mkfs.ext4 /dev/md0p1 && mkfs.ext4 /dev/md0p2 && mkfs.ext4 /dev/md0p3 && mkfs.ext4 /dev/md0p4 && mkfs.ext4 /dev/md0p5 && mkdir -p /mnt/otus{1..5} && echo /dev/md0p1 /mnt/otus1 ext4  rw,user,exec 0 0 >> /etc/fstab && echo /dev/md0p2 /mnt/otus2 ext4  rw,user,exec 0 0 >> /etc/fstab && echo /dev/md0p3 /mnt/otus3 ext4  rw,user,exec 0 0 >> /etc/fstab && echo /dev/md0p4 /mnt/otus4 ext4  rw,user,exec 0 0 >> /etc/fstab && echo /dev/md0p5 /mnt/otus5 ext4  rw,user,exec 0 0 >> /etc/fstab && mount -a
  	  SHELL

      end
  end
end

