---
- name: install chrony
  yum:
   name: ['chrony']
   state: present

- name: disable ntp
  ignore_errors: True
  service:
   name: ntpd
   state: stopped
   enabled: no

- name: Make override dir for service chronyd
  file:
   path: /etc/systemd/system/chronyd.service.d
   state: directory

- name: Enable autorestart of services
  copy:
   src: override.conf
   dest: /etc/systemd/system/chronyd.service.d/override.conf

- name: start chronyd
  service:
   name: chronyd
   state: restarted
   enabled: yes
