---
  - name: install chrony
    yum: 
     name: ['chrony']
     state: latest 

  - name: disable ntp
    ignore_errors: True
    service:
     name: ntpd
     state: stopped
     enabled: no

  - name: start chronyd
    service:
     name: chronyd
     state: restarted
     enabled: yes
