---
 - name: install standart packages
   yum: name={{ item }} state=latest 
   with_items:
    - audispd-plugins
 - name: copy au-remote.conf
   copy: src=au-remote.conf dest=/etc/audisp/plugins.d/au-remote.conf
 - name: copy audisp-remote.conf
   copy: src=audisp-remote.conf dest=/etc/audisp/audisp-remote.conf
 - name: copy auditd.conf
   copy: src=auditd.conf dest=/etc/audit/auditd.conf 
