---

- name: restart proxysql service
  systemd:
    enabled: "{{ proxysql_service_enabled_state | default('yes') }}"
    name: proxysql
    state: "{{ proxysql_service_state | default('restarted') }}"
