---
- name: Install fail2ban
  yum:
   name: ['fail2ban']
   state: present
   
- name: copy filters
  copy: src={{ item }} dest=/etc/fail2ban/filter.d/
  with_fileglob:
   - nginx-*
     
- name: copy jail.local
  copy: src=jail.local dest=/etc/fail2ban/jail.local

- name: start fail2ban
  service:
   name: fail2ban
   state: restarted
   enabled: yes

