# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:openvpn1 => {
		:box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                 {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "internet"},
                 {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "openvpn1-net"},
                ]
  },
:openvpn2 => {
        :box_name => "centos/7",
        :net => [
                 {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "internet"},
                 {ip: '192.168.2.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "openvpn2-net"},
                     ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                yum -y install epel-release
                yum -y install openvpn bridge-utils policycoreutils-python
                echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
                sysctl --system
        SHELL
        
		case boxname.to_s
		when "openvpn1"
			box.vm.provision "shell", inline: <<-SHELL

			SHELL
		when "openvpn2"
			box.vm.provision "shell", inline: <<-SHELL
			SHELL
    end

      end

  end
  
  
end

