---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: zabbix-agent-centos
    image: milcom/centos7-systemd:latest
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-debian-jessie
    image: maint/debian-systemd:latest
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-debian-stretch
    image: jrei/systemd-debian:latest
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-ubuntu-xenial
    image: solita/ubuntu-systemd:xenial
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-mint
    image: vcatechnology/linux-mint
    groups:
      - group1
    privileged: True
  - name: zabbix-agent-ubuntu-bionic
    image: solita/ubuntu-systemd:bionic
    groups:
      - group1
    privileged: True

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
