---
# systemd-tmpfiles
- name: systemd-tmpfiles-create
  shell: systemd-tmpfiles --create
  tags:
  - skip_ansible_lint

- name: restart service lsyncd
  service: name=lsyncd-{{ cluster_web_server }} state=started enabled=yes
