---
- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/home/wordpress

- name: Download WordPress
  get_url:
   url: https://ru.wordpress.org/wordpress-{{ wp_version }}-ru_RU.tar.gz
   dest: /srv/wordpress-{{ wp_version }}.tar.gz
   checksum: sha256:{{ wp_sha256sum }}

- name: Extract archive
  unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/
    remote_src: yes

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  warn: False
  tags:
  - skip_ansible_lint

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes

- name: install SEManage
  yum: pkg=policycoreutils-python state=present

- name: set the SELinux policy for the Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/wordpress(/.*)?"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-config\.php"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content(/.*)?"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for the *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/.*\.php"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for the Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/upgrade(/.*)?"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for the Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/uploads(/.*)?"
  tags:
  - skip_ansible_lint

- name: set the SELinux policy for the wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-includes/.*\.php"
  tags:
  - skip_ansible_lint

- name: set the SELinux on all the Files
  command: restorecon -Rv /srv/wordpress
  tags:
  - skip_ansible_lint
