---
  - name: reload postfix
    service: name=postfix state=reloaded
  - name: reload dovecot
    service: name=dovecot state=reloaded
#  - name: reload mariadb
#    service: name=mariadb state=restart
