---
  - name: create vmail group
    group:
     name: vmail

  - name: Add the user 'vmail'
    user:
     name: vmail
     group: vmail
     home: /var/vmail
     shell: /sbin/nologin

  - name: install postfix
    yum: name=postfix state=present
  - name: install dovecot
    yum: name=dovecot state=present
  - name: install epel-release
    yum: name=epel-release state=present
  
  - name: Postfix Configuration
    template: src=postfix/{{item}} dest=/etc/postfix/{{item}} owner=root group=root mode=0644
    with_items:
      - main.cf
      - master.cf
    notify:
      - reload postfix
      
  - name: add dovecot user
    script: add_user.sh "{{ name }}" "{{ password }}"
        
  - name: Dovecot Configuration
    template: src=dovecot/{{item}} dest=/etc/dovecot/{{item}} owner=root group=root mode=0644
    with_items:
      - dovecot.conf
    notify:
      - reload dovecot
  - name: start services
    service: name={{item}} state=started
    with_items:
      - postfix
      - dovecot
