# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_user_privileges}}"
  when: postgresql_users|length > 0

    
- name: create pgpass file for user
  template: src=pgpass.j2 dest="/home/{{ pgpass_username }}/.pgpass" owner="{{ pgpass_username }}" group="{{ pgpass_username }}" mode=600
  
- name: create pgpass file for root
  template: src=pgpass_root.j2 dest="/root/.pgpass" owner="root" group="root" mode=600
  
- name: change peer to md5
  shell: find {{postgresql_conf_directory}}/pg_hba.conf -type f -print0 | xargs -0 sed -i 's/local  all  all    peer/local  all  all    md5/g'
  
- name: PostgreSQL | Reload all conf files
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
