---
# tasks file for wdijkerman.zabbix

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Debian.yml"
  when:
    - ansible_os_family == "Debian"

- name: "Installing the postgresql database"
  include: "postgresql.yml"
  when:
    - zabbix_server_database_long == "postgresql"

- name: "Installing the mysql database"
  include: "mysql.yml"
  when:
    - zabbix_server_database_long == "mysql"

- name: "Configure zabbix-server"
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: 0644
  notify:
    - zabbix-server restarted
  tags:
    - zabbix-server
    - init
    - config

- name: "Create include dir zabbix-server"
  file:
    path: "{{ zabbix_server_include }}"
    owner: zabbix
    group: zabbix
    state: directory
    mode: 0755
  tags:
    - zabbix-server
    - init
    - config

- name: "Zabbix-server started"
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
  when:
    - ansible_distribution != 'Ubuntu' or (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('14.04', '>'))
  tags:
    - zabbix-server

- name: "Zabbix-server started for Ubuntu"
  service:
    name: zabbix-server
    state: started
    enabled: yes
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('14.04', '<=')
  tags:
    - zabbix-server
