---
# playbook.yml file.
- hosts: all
  become: yes
  roles:
   - sysctl
   - packages
   - chrony
   - liquidprompt
#   - fail2ban

- hosts: webservers
  become: yes
  roles:
   - mariadb
   - nginx
   - php-fpm
   - wordpress
   - lsyncd


- hosts: lblservers
  user: root
  become: true
  become_user: root
  roles:
   - haproxy

- hosts: keepalived_master
  user: root
  become: true
  become_user: root
  roles:
   - keepalived
  vars:
   interface: eth1
   virtual_router_id: 1
   virtual_ipaddress: 10.0.5.81
   priority: 101
   secret_passwd: ZcnG9lGUoZeM3nFT

- hosts: keepalived_backup
  user: root
  become: true
  become_user: root
  roles:
   - keepalived
  vars:
   interface: eth1
   virtual_router_id: 1
   virtual_ipaddress: 10.0.5.81
   priority: 100
   secret_passwd: ZcnG9lGUoZeM3nFT
