---
  - name: install epel
    yum: name={{ item }} state=latest 
    with_items:
     - epel-release
  - name: install standart packages
    yum: name={{ item }} state=latest 
    with_items:
     - htop
     - ncdu
     - iotop
     - iftop
     - bind-utils
     - traceroute
     - mc
     - nano
     - tmux
     - bash-completion
     - bash-completion-extras
     - yum-utils
     - deltarpm
     - lsof
     - gdb
     - curl
     - wget
     - git
     - net-tools
     - iperf
     - nmap
     - policycoreutils-python
     - setools-console
