---
# Tasks specific for OpenSuse Systems

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Install zypper repo dependency"
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - python-libxml2
    - python-xml
  become: yes
  register: dependency

- name: "Suse | Install basic repo file"
  zypper_repository:
    repo: "{{ suse[ansible_distribution][ansible_distribution_major_version]['url'] }}"
    name: "{{ suse[ansible_distribution][ansible_distribution_major_version]['name'] }}"
    state: present
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install zabbix-agent"
  zypper:
    name: "{{ item }}"
    state: "{{ zabbix_agent_package_state }}"
    disable_gpg_check: yes
  with_items: "{{ zabbix_agent_packages }}"
  become: yes
  tags:
    - zabbix-agent
    - init
