# file: postgresql/tasks/main.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
  tags: [always]

- import_tasks: install_yum.yml
  when: ansible_pkg_mgr == "yum" and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" )
  tags: [postgresql, postgresql-install]

#- import_tasks: tune.yml
#  when: postgresql_tune_server_use != false
#  tags: [postgresql, postgresql-configure]

#- import_tasks: configure.yml
#  tags: [postgresql, postgresql-configure]

#- import_tasks: users.yml
#  tags: [postgresql, postgresql-users]

#- import_tasks: databases.yml
#  tags: [postgresql, postgresql-databases]

#- import_tasks: schemas.yml
#  tags: [postgresql, postgresql-schemas]

#- import_tasks: users_privileges.yml
#  tags: [postgresql, postgresql-users]

- import_tasks: init_backup.yml
