# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mc='mc -x'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

alias mytuner='curl -sL https://raw.github.com/major/MySQLTuner-perl/master/mysqltuner.pl | perl'
alias myprimer='curl -sL https://raw.githubusercontent.com/RootService/tuning-primer/master/tuning-primer.sh | bash'
[[ $- = *i* ]] && source /opt/liquidprompt/liquidprompt

