# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:testServer1 => {
    :box_name => "centos/7",
    :net => [
             {ip: '172.16.12.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet:  "link1-3"},
             {ip: '172.16.12.5', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet:  "link1-2"},
    ]
},

:testServer2 => {
    :box_name => "centos/7",
    :net => [
             {ip: '172.16.12.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet:  "link1-2"},
             {ip: '172.16.12.9', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet:  "link2-3"},
    ]
},


:testServer3 => {
    :box_name => "centos/7",
    :net => [
             {ip: '172.16.12.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet:  "link1-3"},
             {ip: '172.16.12.10', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet:  "link2-3"},
             ]
},



}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                setenforce 0
                echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1\nnet.ipv4.conf.all.rp_filter = 0' >> /etc/sysctl.d/99-override.conf
                sysctl --system
                yum install quagga nano -y

        SHELL
        
		case boxname.to_s
    when "testServer1"
		box.vm.provision "shell", inline: <<-SHELL
		cp -f /vagrant/quagga/zebra1.conf /etc/quagga/zebra.conf
		cp -f /vagrant/quagga/ospfd1.conf /etc/quagga/ospfd.conf
		chown quagga:quaggavt /etc/quagga/zebra.conf
	chown quagga:quaggavt /etc/quagga/ospfd.conf
	echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
	systemctl restart network
      systemctl enable zebra.service 
      systemctl restart zebra.service
      systemctl enable ospfd.service 
      systemctl restart ospfd.service
      SHELL
    when "testServer2"
		box.vm.provision "shell", inline: <<-SHELL
		cp -f /vagrant/quagga/zebra2.conf /etc/quagga/zebra.conf
		cp -f /vagrant/quagga/ospfd2.conf /etc/quagga/ospfd.conf
		chown quagga:quaggavt /etc/quagga/zebra.conf
			chown quagga:quaggavt /etc/quagga/ospfd.conf
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			systemctl restart network
			systemctl enable zebra.service 
			systemctl restart zebra.service
			systemctl enable ospfd.service 
			systemctl restart ospfd.service
      SHELL
		when "testServer3"
		box.vm.provision "shell", inline: <<-SHELL
		cp -f /vagrant/quagga/zebra3.conf /etc/quagga/zebra.conf
		cp -f /vagrant/quagga/ospfd3.conf /etc/quagga/ospfd.conf
		chown quagga:quaggavt /etc/quagga/zebra.conf
		chown quagga:quaggavt /etc/quagga/ospfd.conf
		echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
		systemctl restart network
		systemctl enable zebra.service 
			systemctl restart zebra.service
			systemctl enable ospfd.service 
			systemctl restart ospfd.service
        SHELL
          end

      end

  end
  
  
end

