---
- name: Copy nginx configuration for kibana
  template: src=default.conf_kibana.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Installing dependencies
  yum: name=python-passlib,policycoreutils-python state=present
  notify: start nginx

- name: Setup htpasswd user for kibana
  htpasswd:
   path: /etc/nginx/htpasswd.kibana
   name: "{{ kibana_user }}"
   password: '{{ kibana_password }}'

- name: Copy nginx configuration for nginx
  template: src=nginx.conf_kibana.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=restarted enabled=yes

- name: insert firewalld rule for nginx
  firewalld: port=9201/tcp permanent=true state=enabled immediate=yes

- name: firewalld open http
  firewalld:
   service: http
   permanent: true
   immediate: true
   state: enabled

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Set nis_enabled flag on and keep it persistent across reboots
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes
