---
#Installing nginx web server server from YUM
- name: Copy nginx configuration for wordpress
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Copy nginx configuration for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=restarted enabled=yes

- name: Firewalld add web zone
  firewalld:
   zone: web
   state: present
   permanent: true

- name: Firewalld service state
  service: name=firewalld state=reloaded enabled=yes

- name: Firewalld add trusted ip to web zone
  firewalld:
   source: "{{ hostvars[ groups['lblservers'][0] ].ansible_ssh_host }}"
   zone: web
   state: enabled
   permanent: true

- name: Firewalld add trusted ip to web zone
  firewalld:
   source: "{{ hostvars[ groups['lblservers'][1] ].ansible_ssh_host }}"
   zone: web
   state: enabled
   permanent: true

- name: insert firewalld rule for nginx
  firewalld:
   port: "{{ nginx_port }}/tcp"
   zone: web
   permanent: true
   state: enabled

- name: Firewalld service state
  service: name=firewalld state=reloaded enabled=yes
