---

galaxy_info:
  author: Timo Runge
  description: >
               This role installs and configures ProxySQL -
               the high performance, high availability, protocol aware proxy for MySQL.
  role_name: proxysql
  license: BSD
  min_ansible_version: 2.5.0
  platforms:
  - name: EL
    versions:
      - 7
  - name: Debian
    versions:
      - jessie
      - stretch
  - name: Ubuntu
    versions:
      - trusty
      - xenial
      - artful
      - bionic
      - cosmic
  galaxy_tags:
    - mysql
    - proxysql
    - sytem
dependencies: []
