---
mysqld:
  server_id: "{{ server_id|int }}"
  datadir: /var/lib/mysql
  log_error: /var/log/mysqld.log
  innodb_buffer_pool_size: 128M
  innodb_log_file_size: 64M
  innodb_flush_method: O_DIRECT
  innodb_flush_log_at_trx_commit: 2
  query_cache_size: 0
  query_cache_type: 0
  performance_schema: OFF
  log_bin:
  innodb_file_per_table:
  pid-file: /var/run/mysql/mysqld.pid 
  character-set-server: utf8
  collation-server: utf8_general_ci
  binlog-format: ROW
  log-slave-updates: true
