---
- name: Setup systemctl
  sysctl:
    name: fs.nr_open
    value: 12000000
    state: present
- name: Setup systemctl
  sysctl:
    name: fs.file-max
    value: 9000000
    state: present
- name: Setup systemctl
  sysctl:
    name: net.core.wmem_max
    value: 16777216
    state: present
- name: Setup systemctl
  sysctl:
    name: net.core.rmem_max
    value: 16777216
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_rmem
    value: 8192 87380 16777216
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_wmem
    value: 8192 65536 16777216
    state: present
- name: Setup systemctl
  sysctl:
    name: net.core.netdev_max_backlog
    value: 8192
    state: present
- name: Setup systemctl
  sysctl:
    name: net.core.somaxconn
    value: 8151
    state: present
- name: Setup systemctl
  sysctl:
    name: net.core.optmem_max
    value: 8192
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 10
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 30
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: 3
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 240
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 8192
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_sack
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_syn_retries
    value: 3
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_synack_retries
    value: 2
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_tw_recycle
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: 3
    state: present
- name: Setup systemctl
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: vm.min_free_kbytes
    value: 67584
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 1024 65535
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_limit_output_bytes
    value: 65536
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_rfc1337
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value:  0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
# don't work in virtualbox
#- name: Setup systemctl
#  sysctl:
#    name: net.netfilter.nf_conntrack_helper
#    value: 0
#    state: present
#- name: Setup systemctl
#  sysctl:
#    name: net.netfilter.nf_conntrack_tcp_timeout_established
#    value: 28800
#    state: present
#- name: Setup systemctl
#  sysctl:
#    name: net.netfilter.nf_conntrack_generic_timeout
#    value: 60
#    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_challenge_ack_limit
    value: 999999999
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    state: present
- name: Setup systemctl
  sysctl:
    name: net.ipv4.tcp_base_mss
    value: 1024
    state: present
- name: Setup systemctl
  sysctl:
    name: net.unix.max_dgram_qlen
    value: 4096
    state: present
