---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: filebeat_install

- include: config.yml
  tags: filebeat_config
  when: filebeat_config_enabled

- include: template.yml
  tags: filebeat_template

- name: Make override dir for service filebeat
  file:
   path: /etc/systemd/system/filebeat.service.d
   state: directory

- name: Enable autorestart of services
  copy:
   src: override.conf
   dest: /etc/systemd/system/filebeat.service.d/override.conf

- name: Ensure Filebeat is enabled and started at boot
  service:
    name: filebeat
    enabled: yes
    state: started
  when: filebeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
