---

samba_packages:
  - samba-common
  - samba
  - samba-client
  - cifs-utils

samba_selinux_packages:
  - libsemanage-python

samba_selinux_booleans:
  - samba_enable_home_dirs
  - samba_export_all_rw

samba_configuration: /etc/samba/smb.conf
samba_username_map_file: /etc/samba/smbusers

samba_services:
  - smb
  - nmb

samba_www_documentroot: /var/www/html
